---
title: "Relational Data with dplyr"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(nycflights13)

View(airlines)
View(airports)
View(planes)
View(weather)

#verify if they are unique keys
planes %>% count(tailnum) %>% filter(n >1)

#not unique
weather %>% count(year, month, day, hour, origin) %>% filter(n>1)


#make unique with row_number() - surrogate key
weather %>% group_by(year,month,day,hour,origin) %>% mutate(rank = row_number())%>% 
  count(year, month, day, hour, origin,rank) %>% 
  filter(n>1)

```
## Exercises

#1
```{r}

View(flights)
flights  %>% mutate(plane_no= row_number()) %>% 
  count(plane_no) %>% 
  filter(n>1)

#what does row_number do
x <- c(1,5,2,3,10,11,8,5)
row_number(x)

flights %>% mutate(plane_id = row_number()) %>% 
  glimpse()

```
#2
```{r}
View(Lahman::Batting)
Lahman::Batting %>% count(playerID,yearID,stint) %>% 
  filter(n>1)

View(babynames::babynames)
babynames::babynames %>% count(year,sex,name) %>% filter(n>1)

nasaweather::atmos %>% count(lat,long,year,month) %>% filter(n>1)

fueleconomy::vehicles
fueleconomy::vehicles %>% count(id,make) %>% filter(n>1)

diamonds
diamonds %>% count(cut,color,clarity) %>% filter(n>1) #no primary keys

diamonds %>% mutate(diamonds_id = row_number()) %>% glimpse

diamonds %>% distinct() %>% nrow()
diamonds %>% nrow() #since both not same, there will be duplicate rows




```
## Mutating joins

```{r}
#since there is a lot of variables, selecting only the required ones to get the point across
#Left Join
flights2 <- select(flights, year:day, hour, origin, dest, tailnum, carrier)
flights2 %>% left_join(airlines, by= "carrier")

#Setting up two tibbles for join operations

x <- tribble(
  ~key, ~value,
  1, "x1",
  2, "x2",
  3, "x3"
)

y <- tribble(
  ~key, ~value,
  1, "y1",
  2, "y2",
  4, "y3"
)

#Inner Join

x %>% inner_join(y, by = "key")

#Left Join, keeps all value in x
x %>% left_join(y, by = "key")
#right join, keeps all value in y
x %>% right_join(y, by = "key")
#full join keeps all values
x %>% full_join(y, by = "key")

#Duplicate Keys

#One table with duplicate keys
x <- tribble(
  ~key, ~val_x,
  1, "x1",
  2, "x2",
  2, "x3",
  1, "x4"
)
y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2"
)
x %>% left_join(y, by = "key")

#Both tables with duplicate keys - it should be an error as no combination can identify any unique observation
x <- tribble(
  ~key, ~val_x,
  1, "x1",
  2, "x2",
  2, "x3",
  3, "x4"
)

y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2",
  2, "y3",
  3, "y4"
)

left_join(x,y, by = "key") #a Cartesian product of all keys

```
#defining key columns

```{r}
flights2 %>% left_join(weather) #by not specifying the by = "", the algorithm identifies common variable and matches accordingly

#by = "a variable name" selects only

#by = c("a"="b") - this will match variable a in table x to b in y

flights2 %>% left_join(airports, c("dest"="faa"))

```

## EXercises
1
```{r}
flights %>% group_by(dest) %>% summarise(delay = mean(arr_delay, na.rm = T)) %>% left_join(airports,by = c("dest" = "faa")) %>% 
  ggplot(aes(lon, lat))+
  borders("state") +
  geom_point(aes(color = delay))+
  coord_quickmap()
```

2
```{r}
View(flights)

airport_locations <- airports %>%
  select(faa, lat, lon)

flights %>%
  select(year:day, hour, origin, dest) %>%
  left_join(
    airport_locations,
    by = c("origin" = "faa")
  ) %>%
  left_join(
    airport_locations,
    by = c("dest" = "faa"),
    suffix = c("_origin", "_dest")
    # existing lat and lon variables in tibble gain the _origin suffix
    # new lat and lon variables are given _dest suffix
  )

```

3
```{r}
plane_cohorts <- inner_join(flights,
  select(planes, tailnum, plane_year = year),
  by = "tailnum"
) %>%
  mutate(age = year - plane_year) %>%
  filter(!is.na(age)) %>%
  group_by(age) %>%
  summarise(
    dep_delay_mean = mean(dep_delay, na.rm = TRUE),
    dep_delay_sd = sd(dep_delay, na.rm = TRUE),
    arr_delay_mean = mean(arr_delay, na.rm = TRUE),
    arr_delay_sd = sd(arr_delay, na.rm = TRUE),
    n_arr_delay = sum(!is.na(arr_delay)),
    n_dep_delay = sum(!is.na(dep_delay))
  )

ggplot(plane_cohorts, aes(x = age, y = dep_delay_mean)) +
  geom_point()

ggplot(plane_cohorts, aes(x = age, y = arr_delay_mean)) +
  geom_point() +geom_smooth()

```

4
```{r}
flight_weather <-
  flights %>%
  inner_join(weather, by = c(
    "origin" = "origin",
    "year" = "year",
    "month" = "month",
    "day" = "day",
    "hour" = "hour"
  ))

flight_weather %>%
  group_by(precip) %>%
  summarise(delay = mean(dep_delay, na.rm = TRUE)) %>%
  ggplot(aes(x = precip, y = delay)) +
  geom_line() + geom_point()

```
5
```{r}
flights %>%
  filter(year == 2013, month == 6, day == 13) %>%
  group_by(dest) %>%
  summarise(delay = mean(arr_delay, na.rm = TRUE)) %>%
  inner_join(airports, by = c("dest" = "faa")) %>%
  ggplot(aes(y = lat, x = lon, size = delay, colour = delay)) +
  borders("state") +
  geom_point() +
  coord_quickmap()
```

## Filtering Joins

```{r}
#semi_join keeps all values that have a matching pair in y. No values copies

#anti_join keeps values that doesn't have a matching pair in y


top_dest <- flights %>% count(dest, sort = T) %>% 
  head(10) #saves top 10 destinations in the variable

#not to get details of the flights going to the top destinations : -
flights %>% semi_join(top_dest)

#anti_join keeps rows that doesn't have a match

#this is used for identifying observations that doesnt have a match

flights %>% anti_join(planes, by = "tailnum") %>% count(tailnum, sort = T)

```

Exercises

1
```{r}
View(flights %>% anti_join(planes, by = "tailnum"))
```
#Exercises to be completed


```{r}

#intersect(x,y) - Return observations in both x and y
# union(x, y) - Return unique observations in x and y
#setdiff(x,y) - Return observations in x. but not in y



```

