---
title: "Factors with forcats"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(forcats)
```
```{r}
x1 <- c("Dec", "Apr", "Jan", "Mar") 
x2 <- c("Dec", "Apr", "Jam", "Mar")
#cannot sort properly and subjected to typos

month_levels <- c(
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
)

y1 <- factor(x1, levels = month_levels)
y1

sort(y1)
y2 <- factor(x2, levels = month_levels) #silently converted to NA
y2
 
#if you want errors, use parse_factor
parse_factor(x2, levels = month_levels)

#if levels omitted, the ones in parameter passed will be the order and level
factor(x1)

f1 <- factor(x1, unique(x1))# match order as what is in the first appearance of data

#to access level directly

levels(y1)
```

# General Social Survey
```{r}
gss_cat

gss_cat %>% count(race) #no NA - but defined
gss_cat %>% ggplot(aes(x = race))+
  geom_bar() +
  scale_x_discrete(drop = F) #otherwise NA will be droppped
```

Exercises

1
```{r}
gss_cat %>% count(rincome)

rincome_plot <- gss_cat %>% ggplot(aes(x = rincome))+
  geom_bar() 
#here there is a lot of factors. And the values overlap one another. 

rincome_plot + coord_flip()

rincome_plot +theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
2
```{r}
gss_cat %>% count(relig) %>% arrange(desc(n))
gss_cat %>% count(partyid) %>% arrange(desc(n))
```
3
```{r}
View(gss_cat)
table(gss_cat$denom, gss_cat$relig)

gss_cat %>% count(relig, denom) %>% 
  ggplot(aes(x = denom, y = relig, size = n)) +
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

Modifying Factor Order
```{r}
relig <- gss_cat %>% group_by(relig) %>% 
  summarize(
    age = mean(age, na.rm = T),
    tvhours = mean(tvhours, na.rm = T),
    n = n()
  )

ggplot(relig, aes(x = tvhours, relig)) +geom_point()

ggplot(relig, aes(tvhours, fct_reorder(relig, tvhours))) +
  geom_point()

ggplot(relig, aes(tvhours, reorder(relig, tvhours))) +
  geom_point() #reorder (factor to reorder, numerical value, funtion)

#as expression become complicated, its better to mutate it outside before passing into the ggplot

relig %>% 
  mutate(relig = reorder(relig, tvhours)) %>%  #arranging wont work as the relig factors are already ordered in a certain way. Need to rearrange level first.
  ggplot(aes(tvhours, relig)) +geom_point()

rincome <- gss_cat %>% 
  group_by(rincome) %>% 
  summarize(
    age = mean(age, na.rm = T),
    tvhours = mean(tvhours, na.rm = T),
    n = n()
  ) 
  
  
rincome %>% mutate(rincome = reorder(rincome, tvhours)) %>% 
  ggplot(aes(tvhours, rincome)) +
  geom_point() #here reordering is not a good idea. rincome is already arranged in a principal order. NOw that got jumbled up.

#here Not applicable should be pulled down

ggplot(rincome, aes(age, fct_relevel(rincome,"Not applicable"))) +
  geom_point()
```

```{r}
by_age <-    gss_cat %>% 
  filter(!is.na(age)) %>% 
  group_by(age, marital) %>% 
  count() %>% group_by(age) %>% mutate(sum = sum(n), prop = n/sum)

#in this plot, color of the lines at highest x(age) doesn't line up
ggplot(by_age, aes(age, prop, color = marital))+
  geom_line(na.rm = T)

#in this plot, the highest the color of the lines get aligned to the legend at the highest x - easier to read
ggplot(
  by_age,
  aes(age, prop, color = fct_reorder2(marital, age, prop))
) +
  geom_line() +
  labs(color = "marital")
```


Modifying Factor Levels

```{r}
gss_cat %>% count(partyid)

gss_cat %>% mutate( partyid = fct_recode( partyid,
        "Republican, strong" = "Strong republican",
        "Republican, weak"  = "Not str republican",
        "Independent, near rep" = "Ind,near rep",
        "Independent, near dem" = "Ind,near dem",
        "Democrat, weak" = "Not str democrat",
        "Democrat, strong" = "Strong democrat"
        )) %>% count(partyid)

#to combine
gss_cat %>% mutate( partyid = fct_recode( partyid,
        "Republican, strong" = "Strong republican",
        "Republican, weak"  = "Not str republican",
        "Independent, near rep" = "Ind,near rep",
        "Independent, near dem" = "Ind,near dem",
        "Democrat, weak" = "Not str democrat",
        "Democrat, strong" = "Strong democrat",
        "Other" = "No answer",
        "Other" = "Don't know",
        "Other" = "Other party"
        )) %>% count(partyid)

#to collapse a lot of factors use colapse
gss_cat %>% mutate(partyid = fct_collapse(partyid,
        "Republican" = c("Strong republican","Not str republican"),
        "Independent" = c("Ind,near rep","Ind,near dem"),
        "Democrat" = c("Not str democrat","Strong democrat"),
        "Other" = c("No answer","Don't know","Other party")
        )) %>% count(partyid)

#to lump small groups until aggregate is still smallest
gss_cat %>% mutate(relig = fct_lump(relig)) %>% 
  count(relig)

#to specify how many group we need, excluding "other"
gss_cat %>% mutate(relig = fct_lump(relig, n =10)) %>% 
  count(relig, sort = T)

```



















































































































