---
title: "Dates and Times with lubridate"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(lubridate)
library(nycflights13)
```
```{r}
today() #today's date
now() #datetime now with Time zone

#Parse from strings
ymd("2017/01/24")
ymd("2017-09-21", tz = "UTC") #can coerce timezones
myd(02199212) #unquoted numbers 
ymd_hms("2018/01/21 20:01:00")
ymd_h("2018/01/21 8 PM")

#parse from Individual Components
flights %>% select(year:day, hour,minute) %>% head(5) %>% 
  mutate(departure = make_datetime(year,month, day, hour, minute))

make_datetime_100 <- function(year, month, day, time) {
  make_datetime(year, month, day, time%/%100, time%%100)
}
flights_dt <- flights %>% 
  filter(!is.na(dep_time), !is.na(arr_time)) %>% 
  mutate(
    dep_time = make_datetime_100(year, month, day, dep_time),
    arr_time = make_datetime_100(year, month, day, arr_time),
    sched_dep_time = make_datetime_100(year, month, day, sched_dep_time),
    sched_arr_time = make_datetime_100(year, month, day, sched_arr_time)
  ) %>% 
  select(origin, dest, ends_with("delay"), ends_with("time"))

#distribution of flights across the year
View(flights_dt)
flights_dt %>% ggplot(aes(dep_time))+
  geom_freqpoly(binwidth = 86400)

#distribution of departure flights in a day
flights_dt %>% filter(dep_time<ymd(20130102)) %>% 
  ggplot(aes(dep_time)) +
  geom_freqpoly(bins = 24*6)

as_datetime(today())
as_date(now())
```

Exercises
1
```{r}
ymd(c("2010-10-10","banana"))
```
3
```{r}
mdy("January 1, 2010")
ymd("2015 - mar - 07")
dmy("06 - Jun - 2017")
mdy(c("Aug 19 (2015", "July 1 (2015"))
mdy("12/30/14")
```

Date-Time Components
```{r}
datetime <- ymd_hms("1992-02-11 1:30:00 PM")
year(datetime)
month(datetime)
mday(datetime)

yday(datetime)
wday(datetime) #Sunday is 1

month(datetime, label = T)
month(datetime, label = T, abbr = F)
wday(datetime, label = T)

flights_dt %>% mutate(
  wday = wday(dep_time, label = T, abbr = F)
) %>% ggplot(aes(x = wday))+
  geom_bar()

flights_dt %>% mutate(minute = minute(dep_time)) %>% 
  group_by(minute) %>% 
  summarise(avg_delay = mean(dep_delay, na.rm = T),
            n = n()) %>%
  ggplot(aes(minute, avg_delay))+
  geom_line()
```

Rounding

```{r}
flights_dt %>% 
  count(week = floor_date(dep_time, "week")) %>% 
  ggplot(aes(week, n)) +
  geom_line()
```

Setting Components

```{r}
(datetime <- ymd_hms("2016/07/08 12.34.00 AM"))
year(datetime) <- 2020
datetime
month(datetime) <- 12
datetime
hour(datetime) <- hour(datetime) + 20
datetime

update(datetime, year = 2019, month = 5, mday = 15, hour =2)
```
Timespans

Durations

```{r}
as.duration(today() - ymd(19920211))

dseconds(10)
dminutes(10)
dhours(c(12,24))
ddays(0:5)
dweeks(3)
dyears(1)


2*dyears(1)
dyears(3) + dweeks(15)+dminutes(500)
today()+ddays(1) #tomorrow


```

 



















