---
title: "Visualization with ggplot, Part 2 - Duplicate of Part 1"
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
ggplot(data = mpg)+
  geom_point(mapping = aes(x =  displ, y = hwy))

```
```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
```

aesthetic - Linetype used
```{r}
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```

```{r}
ggplot(data = mpg) + 
  geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv, color = drv))
```
```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
```

```{r}
ggplot(data = mpg)+
  geom_smooth(mapping = aes(x = displ, y = hwy, color = drv))
```
```{r}
ggplot(data = mpg)+
  geom_smooth(mapping = aes(x = displ, y = hwy))+
  geom_point(mapping = aes(x = displ, y = hwy))
```
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv))+
  geom_smooth()+
  geom_point()
```
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy))+
  geom_smooth(mapping = aes(color = drv))+
  geom_point()
```
```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy))+
  geom_smooth(data = filter(mpg, class == "subcompact"),
              se = FALSE)+
  geom_point(mapping = aes(color = class))
```

