---
  title: "Visualization with ggplot, Part 1"
---


```{r}
library(tidyverse)
mpg

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  labs(x = "Engine Displacement (L)", y = " Mileage per Gallon, Highway", 
       title = "Mileage VS Engine Displacement", caption = "Random Stuffs for ggplot2", subtitle = "A Simple Good Graph")

ggplot(mpg, aes(x = cyl, y = hwy)) +
  geom_point()
```

## Aesthetic Mappings 
#### All this will go inside aes()
  + size(in mm)
  + color/colour("")
  + alpha(transparency)
  + shape [0-24]
  + fill("color") and stroke(in mm)
  

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(color = class))

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(alpha = class))

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(shape = class)) #only selects 6 shapes and ignores the rest

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(mapping = aes(size = class))

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(shape = 21, fill = "red", stroke = 2)

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(color = "green", size = 2)

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(color = displ < 5)) # Conditional Aesthetic
```
## Facets - wrap and grid

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() +
  facet_wrap(~class, nrow = 3)

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() + 
  facet_grid(drv~cyl) 

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point() + 
  facet_grid(.~cyl)
```

## Geometric Objects
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth()

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(group = drv))

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(color = drv))

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(aes(linetype = drv), show.legend = FALSE)

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(se = FALSE) +
  geom_point(aes(color = drv))

ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(data = filter(mpg, class == "midsize")) +
  geom_point(aes(color = class))
```




