---
title: "Transformation with dplyr, Part 3"
author: "Vineed"
date: "5/18/2020"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Select columns with select()
```{r}
library(tidyverse)
library(nycflights13)

select(flights, year, month, day)
select(flights, year:day) #both same

select(flights, -(year:day))
```

* helper functions that can be used with select variablesare :- 
    + starts_with("abc") - variables with abc starting
    + ends_with("xyz")
    + contains("ijk")
    + matches("(.)\\1") - needs more clarity, chapter 11
    + num_range("X", 1:3) for x1, x2, x3

```{r}

select(flights, starts_with("arr"))


```

> Renaming variables using select and rename

```{r}
select(flights, tail_num = tailnum) #selects only that variable
rename(flights, tail_num = tailnum) #the whole tiblle is selected. And the variable renamed too.

select(flights, starts_with("arr"), starts_with("dep"), everything()) #used for rearranging the variables. Here all the selected columns come to the right and the remaining after that.

```

## Exercises

1
```{r}
select(flights, dep_time, dep_delay, arr_time, arr_delay)
select(flights, starts_with("dep"),starts_with("arr"))

```
2
```{r}
select(flights, distance, distance)

```

3
```{r}
vars <- c("year", "month", "day", "dep_delay", "arr_delay")
select(flights, one_of(vars)) #even if vars was a variable, the values in vars will be selected
select(flights, vars) #if vars was a variable, then only vars will be selected

```


